services:
  - type: web
    name: shoes-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 8373827418:AAH6C7xavJyMQFy6VGLlD3jfn1hHmDGjSXg
      - key: WEBHOOK_SECRET
        value: "shoes-secret-2025"